language: generic
before_install: true
install: true
before_script: 
  - echo "Before Script"
  - export NODE_OPTIONS=--max_old_space_size=8192
script: 
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - if [ "$TRAVIS_PULL_REQUEST" == false ]; then bash ./deploy.sh; else bash ./build.sh; fi